# Матрицы и векторы

In [1]:
import numpy as np

## 1. Скалярное умножение векторов

$$(a, b) = \sum a_i b_i$$

In [74]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

In [70]:
a

array([1, 2, 3])

In [3]:
np.dot(a, b)

26

Реализуем скалярное произведение средствами Python

In [4]:
sum([x * y for x, y in zip(a, b)])

26

Примеры:

Следующие два примера – ортогональные векторы

In [5]:
np.dot([0, 1], [1, 0])

0

In [6]:
np.dot([3, 1, 2], [-1, 1, 1])

0

In [7]:
np.dot([1, 2, 3], [2, 4, 6])

28

In [8]:
np.dot([-10, -1], [1, 1])

-11

## 2. Длина вектора через скалярное произведение

$$\lvert a\lvert= \sqrt{(a, a)}$$

In [76]:
a

array([1, 2, 3])

In [77]:
np.sqrt(np.dot(a, a))

3.7416573867739413

In [78]:
np.linalg.norm(a)

3.7416573867739413

In [11]:
np.linalg.norm([0, 1])

1.0

In [12]:
np.linalg.norm([3, 4])

5.0

In [13]:
np.linalg.norm([-1, -1])

1.4142135623730951

In [14]:
np.sqrt(2)

1.4142135623730951

## 3. Сложение матриц и умножение на число

Матрицы складываются поэлементно. При умножении на число все элементы матрицы умножаются на это число.

In [112]:
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 2))

In [91]:
a, b

(array([[1, 0],
        [7, 5]]),
 array([[8, 4],
        [3, 7]]))

In [92]:
a + b

array([[ 9,  4],
       [10, 12]])

In [93]:
a

array([[1, 0],
       [7, 5]])

In [94]:
a * 2

array([[ 2,  0],
       [14, 10]])

$I$ или $E$ – единичная матрица

In [99]:
eye_matrix = np.eye(3)

In [100]:
eye_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
eye_matrix * 5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

## 4. Умножение матриц

Для умножения нужно, чтобы **средние** размерности совпадали: умножить можно только $n*k$ на $k*m$  
Под средними размерностями подразумеваются те размерности, которые находятся посередине при записи размерностей двух матриц. В примере выше это *k*

In [101]:
a

array([[1, 0],
       [7, 5]])

In [102]:
b

array([[8, 4],
       [3, 7]])

Проверим на первой строке первой матрицы и на первом столбце второй матрицы  
**1, 1** – первая строка первой матрицы, первый столбец второй матрицы  
([1 0], [8 3]) – скалярное произведение этих векторов

1\*8 + 0\*3 = 8


**1, 2**  
([1, 0], [4, 7])  
1\*4 + 0\*7 = 4

In [115]:
np.dot(a, b)

array([[63, 69],
       [72, 76]])

In [113]:
a @ b

array([[63, 69],
       [72, 76]])

In [114]:
np.matmul(a, b)

array([[63, 69],
       [72, 76]])

dot и matmul работают одинаково для 2д матриц, но matmul не позволяет перемножать скаляры и работает по-другому для измерений 3+

In [116]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (5, 3))

In [119]:
a, b

(array([[1, 1, 0, 2, 3],
        [1, 2, 0, 1, 2]]),
 array([[1, 0, 1],
        [0, 2, 0],
        [4, 4, 4],
        [0, 3, 1],
        [3, 0, 3]]))

In [117]:
result = np.matmul(a, b)

In [121]:
result

array([[10,  8, 12],
       [ 7,  7,  8]])

Размерность:

In [122]:
result.shape

(2, 3)

## 5. Связь со скалярным произведением

In [123]:
result

array([[10,  8, 12],
       [ 7,  7,  8]])

In [127]:
# i = 1, j = 2
result[1, 2]

8

In [125]:
a, b

(array([[1, 1, 0, 2, 3],
        [1, 2, 0, 1, 2]]),
 array([[1, 0, 1],
        [0, 2, 0],
        [4, 4, 4],
        [0, 3, 1],
        [3, 0, 3]]))

In [128]:
np.dot(a[1,:], b[:, 2])

8

В результате умножения матриц в элементе с индексом (i, j) лежит скалярное произведение i-й строки первой матрицы на j-й столбец второй матрицы

## 6. Умножение матриц некоммутативно

Если средние размерности не совпадают, то умножить вообще нельзя:

Перемножение скаляров коммутативно:

In [129]:
2 * 3 == 3 * 2

True

In [130]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (4, 3))
np.dot(a, b)

ValueError: shapes (2,5) and (4,3) not aligned: 5 (dim 1) != 4 (dim 0)

Средние размерности совпадают, но размерности матриц разные:

In [131]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (5, 3))

In [135]:
np.dot(a, b)

array([[25, 25, 18],
       [10, 18, 13]])

In [136]:
np.dot(b, a)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

Размерности матриц одинаковые:

In [137]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))

In [138]:
a, b

(array([[0, 1],
        [3, 1]]),
 array([[0, 1],
        [2, 4]]))

In [139]:
np.dot(a, b)

array([[2, 4],
       [2, 7]])

In [140]:
np.dot(b, a)

array([[ 3,  1],
       [12,  6]])

## 7. Умножение матриц ассоциативно

$$(AxB)xC==Ax(BxC)$$

In [141]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))
c = np.random.randint(0, 5, (2, 2))

In [142]:
np.dot(np.dot(a, b), c) == np.dot(a, np.dot(b, c))

array([[ True,  True],
       [ True,  True]])

## 8. Вычисление определителей

In [145]:
a = np.random.randint(0, 5, (2, 2))
a

array([[0, 1],
       [3, 2]])

In [146]:
det = a[0, 0]*a[1, 1] - a[1, 0]*a[0, 1]
det

-3

In [147]:
np.linalg.det(a)

-3.0000000000000004

Примеры:

In [148]:
# Вторая строка равна первой, умноженной на 2 – строки линейно зависимы
np.linalg.det(np.array([[1, 2], [2, 4]]))

0.0

In [149]:
# Диагональная матрица, поэтому произведение элементов на диагонали
np.linalg.det(np.array([[2, 0], [0, 3]]))

6.0

In [46]:
np.array([[2, 2], [0, 3]])

array([[2, 2],
       [0, 3]])

In [150]:
# Верхнетреугольная матрица, поэтому произведение элементов на диагонали
np.linalg.det(np.array([[2, 2], [0, 3]]))

6.0

## 9. Определитель произведения матриц

$$det(A*B)=det(A)*det(B)$$

In [153]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))

In [154]:
a, b

(array([[2, 3],
        [4, 0]]),
 array([[1, 0],
        [1, 3]]))

In [156]:
np.linalg.det(np.dot(a, b))

-36.0

In [157]:
np.linalg.det(a) * np.linalg.det(b)

-36.00000000000001

## 10. Единичная и обратная матрицы

Вычисления работают для квадратных матриц. Если определитель равен 0, обратной матрицы не существует.

$$A \cdot A^{-1} = E$$

In [158]:
a

array([[2, 3],
       [4, 0]])

In [159]:
np.linalg.det(a)

-12.0

In [160]:
np.linalg.inv(a)

array([[ 0.        ,  0.25      ],
       [ 0.33333333, -0.16666667]])

In [161]:
np.dot(np.linalg.inv(a), a)

array([[1., 0.],
       [0., 1.]])

In [162]:
np.linalg.det(np.array([[1, 2], [2, 4]]))

0.0

In [163]:
np.linalg.inv(np.array([[1, 2], [2, 4]]))

LinAlgError: Singular matrix

## 11. Коммутативность прямой и обратной матрицы

$$A \cdot A^{-1} = A^{-1} \cdot A  = E$$

In [164]:
a

array([[2, 3],
       [4, 0]])

In [165]:
inv_a = np.linalg.inv(a)

In [166]:
inv_a

array([[ 0.        ,  0.25      ],
       [ 0.33333333, -0.16666667]])

In [169]:
np.dot(a, inv_a).astype(int)

array([[1, 0],
       [0, 1]])

In [168]:
np.dot(inv_a, a)

array([[1., 0.],
       [0., 1.]])

## 12. Поиск обратной матрицы методом Крамера

In [62]:
def matrix_inverse(m):
    # только 2D
    determinant = np.linalg.det(m)
    return [[m[1][1]/determinant, -1*m[0][1]/determinant],
            [-1*m[1][0]/determinant, m[0][0]/determinant]]

In [170]:
a

array([[2, 3],
       [4, 0]])

In [171]:
np.linalg.inv(a)

array([[ 0.        ,  0.25      ],
       [ 0.33333333, -0.16666667]])

In [172]:
np.array(matrix_inverse(a))

array([[-0.        ,  0.25      ],
       [ 0.33333333, -0.16666667]])

## 13. Тензорное произведение векторов

Как работает:

$$a = 
\begin{pmatrix}
a_1 & a_2
\end{pmatrix}$$

$$b = 
\begin{pmatrix}
b_1 & b_2
\end{pmatrix}$$

$$
c = a \space tensordot \space b = 
\begin{pmatrix}
a_1 \cdot [b_1, b_2] \\
a_2 \cdot [b_1, b_2] \\
\end{pmatrix}
$$

In [176]:
a = np.random.randint(0, 10, size=2)
b = np.random.randint(0, 10, size=2)

In [177]:
a, b

(array([7, 9]), array([3, 7]))

In [186]:
np.tensordot(a, b, axes=1)

array(84)

Ссылка: https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

Посмотрим как делать slice в тензоре

In [191]:
test = np.random.randint(0, 10, size=(2, 2, 3))

In [192]:
test

array([[[9, 9, 7],
        [9, 7, 8]],

       [[5, 4, 6],
        [4, 6, 6]]])

In [194]:
test[:, :, 1]

array([[9, 7],
       [4, 6]])

# Немного про lambda-функции

In [180]:
test = lambda x: x + 2

In [183]:
def plus_2(x): return x + 2

In [185]:
list(map(lambda x: x + 2, [1, 2, 3]))

[3, 4, 5]