In [39]:
import numpy as np
A = np.array([[1, 4, 5],
    [-5, 8, 9],
    [-6, 7, 11]]) # создаем матрицу 3х3 
B = np.linalg.eig(A) # находим собственные вектора (с.в.) и собственные числа (с.ч.) через np.linalg.eig
B
# Обратите внимание, что B - кортеж (tuple). Его компоненты имеют тип np.ndarray, с которыми вы уже должны быть знакомы. 
# Нулевая компонента B[0] - вектор собственных чисел, а компонента B[1] - матрица, столбцами которой являются 
# собственные вектора, соответствующие данному числу.; в данном случае собственному числу 13.59373746 
# соответствует собственный вектор [0.45145779, 0.62348353, 0.63832135]

(array([13.59373746,  5.03209301,  1.37416954]),
 array([[ 0.45145779,  0.83661458,  0.10258363],
        [ 0.62348353,  0.44632316, -0.77299039],
        [ 0.63832135,  0.31760303,  0.62606905]]))

In [1]:
import numpy as np
A = np.array([[1, 0.8],
    [0.8, 1,]]) # создаем матрицу 3х3 
B = np.linalg.eig(A) # находим собственные вектора (с.в.) и собственные числа (с.ч.) через np.linalg.eig
B

(array([1.8, 0.2]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [2]:
A = np.array([[1, 0.9922],
    [0.9922, 1,]]) # создаем матрицу 3х3 
B = np.linalg.eig(A) # находим собственные вектора (с.в.) и собственные числа (с.ч.) через np.linalg.eig
B

(array([1.9922, 0.0078]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [15]:
x1 = np.array([1,2,1,1])
x2 = np.array([70,130,62,60])
x1_st = (x1 - x1.mean())/np.linalg.norm(x1 - x1.mean())
x2_st = (x2 - x2.mean())/np.linalg.norm(x2 - x2.mean())
c = 0.70710678*x1_st + 0.70710678*x2_st
c_st = c/np.linalg.norm(c)
np.round(c_st, 4)

array([-0.2359,  0.8642, -0.3054, -0.3228])