In [71]:
import numpy as np
import pandas as pd

In [13]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [14]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10])

In [35]:
a = np.empty(5, dtype=int).tolist()
# одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
print(a)

[94069426632364, 0, 139823513954608, 139823494977328, 48]


In [5]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [10]:
np.linspace(0, 1, 10)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.random.randint(0, 10, (3, 3))  
# массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[5, 4, 6],
       [0, 5, 7],
       [7, 3, 1]])

In [38]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [37]:
np.array([i for i in range(11) if i%2]) 

array([1, 3, 5, 7, 9])

In [41]:
np.array(range(1, 301, 7))

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92,  99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169, 176,
       183, 190, 197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267,
       274, 281, 288, 295])

In [43]:
np.array([x for x in range(1, 301, 7) if x%10 == 7])

array([ 57, 127, 197, 267])

In [44]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
my_array[5]

5

In [46]:
my_array[-1]

9

In [47]:
my_array[3:6]

array([3, 4, 5])

In [48]:
my_array[1:8:3]

array([1, 4, 7])

In [49]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [50]:
my_array[1][2]

12

In [51]:
my_array[1,2]

12

In [52]:
my_array[1]

array([10, 11, 12, 13])

In [53]:
my_array[:,2]

array([ 3, 12, 47])

In [54]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

In [55]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
print(first_line)
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
print(second_line)
third_line = [x**2 for x in range(51)]
print(third_line)

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
print(big_secret)

[14, 10, 6, 56, 40, 24, 98, 70, 42, 140, 100, 60, 182, 130, 78, 224, 160, 96, 266, 190, 114, 308, 220, 132, 350, 250, 150, 392, 280, 168, 434, 310, 186, 476, 340, 204, 518, 370, 222, 560, 400, 240, 602, 430, 258, 644, 460, 276, 686, 490, 294]
[31.622776601683793, 31.654383582688826, 31.68595903550972, 31.71750305430741, 31.74901573277509, 31.78049716414141, 31.811947441173732, 31.843366656181317, 31.874754901018456, 31.906112267087632, 31.937438845342623, 31.96873472629156, 32.0, 32.03123475609393, 32.0624390837628, 32.09361307176243, 32.12475680841802, 32.155870381627054, 32.18695387886216, 32.218007387174026, 32.2490309931942, 32.28002478313795, 32.31098884280702, 32.341923257592455, 32.37282811247729, 32.4037034920393, 32.43454948045371, 32.46536616149585, 32.49615361854384, 32.526911934581186, 32.55764119219941, 32.58834147360065, 32.61901286060018, 32.64965543462902, 32.68026927673638, 32.71085446759225, 32.7414110874898, 32.77193921634788, 32.802438933713454, 32.83291031876401, 3

In [61]:
big_secret_01 = big_secret[:,-1]
big_secret_01.sum()

3154.332495807108

In [66]:
big_secret_02 = big_secret[:,:5]
print(big_secret_02)
np.sum(np.diag(big_secret_02))

[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]


121.37188663699624

In [70]:
big_secret_03 = big_secret[:,-5:]
print(big_secret_03)
np.prod(np.diag(big_secret_03))

[[ 460.          276.          686.          490.          294.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [2116.         2209.         2304.         2401.         2500.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [ 460.          276.          686.          490.          294.        ]]


341505315559.2347

In [72]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[ 9, 51,  7,  7, 87, 13],
       [80, 45, 24, 13, 40, 53],
       [36, 37, 63, 92, 12, 22],
       [17, 86, 68, 85, 92,  8]])

In [73]:
'''Выделим из созданного массива квадрат 2 х 2, содержащий 4 элемента, расположенные в центре матрицы:'''
my_slice = my_array[1:3, 2:4]
my_slice

array([[24, 13],
       [63, 92]])

In [74]:
my_slice[:] = 0
my_array

array([[ 9, 51,  7,  7, 87, 13],
       [80, 45,  0,  0, 40, 53],
       [36, 37,  0,  0, 12, 22],
       [17, 86, 68, 85, 92,  8]])

In [99]:
big_secret[::2,::2] = -1
big_secret[1::2,1::2] = 1
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [104]:
big_secret[:,:5]

array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

In [101]:
np.sum(np.diag(big_secret[:,:5]))

-1.0

In [102]:
np.sum(np.diag(big_secret[:,-5:]))

-1.0

In [103]:
big_secret[:,-5:]

array([[-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.20900000e+03, -1.00000000e+00,
         2.40100000e+03, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00]])

In [105]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [106]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [107]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [108]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[6, 9, 7, 3, 5],
       [7, 7, 9, 1, 1],
       [5, 6, 0, 9, 3],
       [1, 1, 6, 6, 1]])

In [109]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[4, 9, 7, 9],
       [7, 1, 8, 3],
       [1, 3, 9, 3]])

In [110]:
my_array<5

array([[ True, False, False, False],
       [False,  True, False,  True],
       [ True,  True, False,  True]])

In [111]:
my_array[my_array<5]

array([4, 1, 3, 1, 3, 3])

In [112]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[4, 7],
       [7, 8],
       [1, 9]])

In [114]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[2, 0, 9, 8, 7, 5],
       [3, 9, 8, 9, 3, 5],
       [7, 8, 5, 3, 0, 4],
       [9, 4, 3, 0, 3, 3]])

In [115]:
np.sort(my_array, axis=1)

array([[0, 2, 5, 7, 8, 9],
       [3, 3, 5, 8, 9, 9],
       [0, 3, 4, 5, 7, 8],
       [0, 3, 3, 3, 4, 9]])

In [116]:
np.sort(my_array, axis=0)

array([[2, 0, 3, 0, 0, 3],
       [3, 4, 5, 3, 3, 4],
       [7, 8, 8, 8, 3, 5],
       [9, 9, 9, 9, 7, 5]])

In [121]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [122]:
np.sum(np.cos(great_secret[0,:]))

0.16006721889793019

In [123]:
np.sum(great_secret[great_secret > 50])

5470.0

In [130]:
great_secret2 = great_secret.flatten()
great_secret2

array([ 0.        ,  4.64158883, 66.66666667,  1.        ,  4.65700951,
       40.        ,  1.41421356,  4.67232873, 67.33333333,  1.73205081,
        4.68754815, 40.4       ,  2.        ,  4.70266938, 68.        ,
        2.23606798,  4.71769398, 40.8       ,  2.44948974,  4.73262349,
       68.66666667,  2.64575131,  4.7474594 , 41.2       ,  2.82842712,
        4.76220316, 69.33333333,  3.        ,  4.77685618, 41.6       ,
        3.16227766,  4.79141986, 70.        ,  3.31662479,  4.80589553,
       42.        ,  3.46410162,  4.82028453, 70.66666667,  3.60555128,
        4.83458813, 42.4       ,  3.74165739,  4.84880759, 71.33333333,
        3.87298335,  4.86294413, 42.8       ,  4.        ,  4.87699896,
       72.        ,  4.12310563,  4.89097325, 43.2       ,  4.24264069,
        4.90486813, 72.66666667,  4.35889894,  4.91868473, 43.6       ,
        4.47213595,  4.93242415, 73.33333333,  4.58257569,  4.94608744,
       44.        ,  4.69041576,  4.95967566, 74.        ,  4.79

In [131]:
great_secret2[150]

7.0710678118654755

In [133]:
great_secret3 = np.sort(great_secret, axis=0)
np.sum(great_secret3[-1,:])

115.12148016521353