In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [3]:
m = np.array([20, 23, 29, 22, 50, 43, 35])
r = np.array([70, 65, 58, 90, 45, 57, 50])
print(m, r)

[20 23 29 22 50 43 35] [70 65 58 90 45 57 50]


In [5]:
np.round(2/7, 2)

0.29

In [13]:
m_avg = np.round(np.mean(m), 2)
m_avg

31.71

In [14]:
r_avg = np.round(np.mean(r), 2)
r_avg

62.14

In [15]:
m_med = np.median(m)
m_med

29.0

In [16]:
r_med = np.median(r)
r_med

58.0

In [23]:
m_sqsum = (m-m_avg)*(m-m_avg)
print(m_sqsum)
m_std_no_corr = np.round(np.sqrt(np.sum(m_sqsum)/7), 2)
print(m_std_no_corr)

[137.1241  75.8641   7.3441  94.2841 334.5241 127.4641  10.8241]
10.61


In [24]:
m_std_corr = np.round(np.sqrt(np.sum(m_sqsum)/6), 2)
print(m_std_corr)

11.46


In [25]:
r_sqsum = (r-r_avg)*(r-r_avg)
print(r_sqsum)
r_std_no_corr = np.round(np.sqrt(np.sum(r_sqsum)/7), 2)
print(r_std_no_corr)
r_std_corr = np.round(np.sqrt(np.sum(r_sqsum)/6), 2)
print(r_std_corr)

[ 61.7796   8.1796  17.1396 776.1796 293.7796  26.4196 147.3796]
13.79
14.89


In [27]:
np.round(np.corrcoef(m,r), 2)

array([[ 1.  , -0.77],
       [-0.77,  1.  ]])

In [28]:
m_1 = np.array([20, 23, 29, 22, 50, 43, 35, 98, 28])
r_1 = np.array([70, 65, 58, 90, 45, 57, 50, 90, 38])
print(np.round(np.mean(m_1), 2))
print(np.round(np.mean(r_1), 2))

38.67
62.56


In [29]:
np.round(np.corrcoef(m_1,r_1), 2)

array([[1.  , 0.31],
       [0.31, 1.  ]])