In [42]:
import numpy as np
import pandas as pd

In [2]:
s=np.array([33,65,50,45])

In [3]:
s[2]

50

In [4]:
len(s)

4

In [6]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [9]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
# Избавимся от старых признаков, посредством функции delete()
apartment = np.delete(apartment, [0, 1])
# И в завершение добавим в конец нашего массива новый признак share_living_space
apartment = np.append(apartment, share_living_space)
apartment

array([5.27731092e-01, 1.15789474e+00, 3.30305533e-05])

In [10]:
a = np.array([[1, 1], [2, 2], [3, 3]])
b = a.flatten()
np.insert(b, [2, 2], [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [11]:
np.insert(b, slice(2, 4), [5, 6])

array([1, 1, 5, 2, 6, 2, 3, 3])

In [12]:
np.insert(b, [2, 2], [7.13, False])

array([1, 1, 7, 0, 2, 2, 3, 3])

In [13]:
x = np.arange(8).reshape(2, 4)
idx = (1, 3)
np.insert(x, idx, 999, axis=1)

array([[  0, 999,   1,   2, 999,   3],
       [  4, 999,   5,   6, 999,   7]])

In [16]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])
round(apartment[1]/apartment[0], 2)

0.53

In [17]:
share_living_space = apartment[1]/apartment[0]
# Избавимся от старых признаков, посредством функции delete()
apartment = np.delete(apartment, [0, 1])
# И в завершение добавим в конец нашего массива новый признак share_living_space
apartment = np.append(apartment, share_living_space)
apartment.shape

(5,)

In [24]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t[5]

28

In [21]:
t.min() == t[0]

True

In [22]:
t[1]

14

In [23]:
t.max()==t[6]

True

In [25]:
a =  np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [26]:
a = np.array([120,45,68])
omega=0.2
a*omega

array([24. ,  9. , 13.6])

In [30]:
x=np.array([5,2])
y=np.array([-5,-11])
print(x+y)
x-y

[ 0 -9]


array([10, 13])

In [31]:
a=np.array([120,150,90])
w=np.array([130,130,130])
eur=72
t=eur*np.array([2,3,2.5])
t

array([144., 216., 180.])

In [32]:
a+w+t

array([394., 496., 400.])

In [33]:
x=np.array([4,5])
y=np.array([2,1])
u=np.array([1,0])
2*x-3*y+5*u

array([7, 7])

In [34]:
m=np.array([3,4,5,9])
s=np.array([1,5,3,6])
400*s-200*m

array([-200, 1200,  200,  600])

In [35]:
x=np.array([4,5,-1])
y=np.array([2,0,1])
np.dot(x,y)

7

In [36]:
x=np.array([4,6,1])
np.sqrt(np.dot(x,x))

7.280109889280518

In [37]:
x=np.array([4,2,-1])
y=np.array([2,0,1])
np.dot(x,y)

7

In [38]:
x=np.array([4,5,-1])
y=np.array([0,0,0])
np.dot(x,y)

0

In [39]:
x=np.array([4,-1])
y=np.array([-1,4])
np.dot(x,y)

-8

In [40]:
x=np.array([4,-1])
y=np.array([1,4])
np.dot(x,y)

0

In [43]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [44]:
np.array(Hut_Paradise_DF['2.Area']-Hut_Paradise_DF['6.Liv.Area'])

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [47]:
np.array(4/10*Hut_Paradise_DF['1.Rent'])

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [54]:
Hut_Paradise_DF['time'] = np.array([10,20,30,15,5,40,20,8,20])
(Hut_Paradise_DF['time']*Hut_Paradise_DF['5.Demo two weeks']).sum()

1348

In [56]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
print(u@v)
print(u@w)
print(v@w)

0
0
0


In [58]:
(2*v-3*w)@u

0

In [64]:
print(np.linalg.norm(u))
print(np.linalg.norm(v))
print(np.linalg.norm(w))
print(np.around(u/np.linalg.norm(u),3))
print(np.around(v/np.linalg.norm(v),3))
print(np.around(w/np.linalg.norm(w),3))

3.4641016151377544
3.0
4.69041575982343
[0.866 0.    0.289 0.289 0.289]
[ 0.     0.333  0.     0.667 -0.667]
[ 0.213 -0.853 -0.213  0.    -0.426]


In [65]:
A=np.matrix('1,-5;2,2;0,3')
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [66]:
A.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])